Repository CristianDavidIppolito/yoMerco, pull requests merged in 2018-07, with the labels that each got.

#2 creating a pull request template
  docs/pull_request_template.md
Labels: enhancement

#4 feat(all): adding issue template
  docs/issue_template.md
Labels: enhancement

#7 Feature/lerna and api package
  .gitignore
  lerna.json
  package.json
  packages/yomerco-api/.editorconfig
  packages/yomerco-api/.gitignore
  packages/yomerco-api/.yo-rc.json
  packages/yomerco-api/client/README.md
  packages/yomerco-api/package-lock.json
  packages/yomerco-api/package.json
  packages/yomerco-api/server/boot/root.js
  packages/yomerco-api/server/component-config.json
  packages/yomerco-api/server/config.json
  packages/yomerco-api/server/datasources.json
  packages/yomerco-api/server/middleware.development.json
  packages/yomerco-api/server/middleware.json
  packages/yomerco-api/server/model-config.json
  packages/yomerco-api/server/server.js
  packages/yomerco-api/yarn.lock
  yarn.lock
Labels: enhancement

#12 Feature/implement husky
  package-lock.json
  package.json
  packages/yomerco-api/package.json
  yarn.lock
Labels: enhancement

#10 feat(api):connecting with db
  packages/yomerco-api/common/models/my-user.js
  packages/yomerco-api/common/models/my-user.json
  packages/yomerco-api/package.json
  packages/yomerco-api/server/datasources.json
  packages/yomerco-api/server/middleware.json
  packages/yomerco-api/server/migrate.js
  packages/yomerco-api/server/model-config.json
  packages/yomerco-api/yarn.lock
  yarn.lock
Labels: enhancement

#14 Feature/new readme
  README.md
  assets/yomerco.png
Labels: enhancement, good first issue, invalid

#16 Update README.md
  README.md
Labels: bug

#18 Feature/new readme
  README.md
  assets/yomerco.png
  packages/yomerco-api/package-lock.json
Labels: bug

#20 feat(api): 19 - adding bootstrap and regenerate scripts
  package.json
  packages/yomerco-api/package-lock.json
Labels: invalid

#21 adding new project
  package.json
  packages/yomerco-api/package-lock.json
  packages/yomerco-web/.gitignore
  packages/yomerco-web/README.md
  packages/yomerco-web/package-lock.json
  packages/yomerco-web/package.json
  packages/yomerco-web/public/favicon.ico
  packages/yomerco-web/public/index.html
  packages/yomerco-web/public/manifest.json
  packages/yomerco-web/public/styles.css
  packages/yomerco-web/src/assets/logo.svg
  packages/yomerco-web/src/index.js
  packages/yomerco-web/src/pages/Home/index.js
  packages/yomerco-web/src/pages/Home/styles.js
  packages/yomerco-web/src/registerServiceWorker.js
  packages/yomerco-web/yarn.lock
Labels: enhancement

#23 Feature/create header
  package-lock.json
  package.json
  packages/yomerco-api/package-lock.json
  packages/yomerco-web/package-lock.json
  packages/yomerco-web/package.json
  packages/yomerco-web/src/assets/Fonts/circular-black.otf
  packages/yomerco-web/src/assets/Fonts/circular-book.otf
  packages/yomerco-web/src/assets/Fonts/circular-medium.otf
  packages/yomerco-web/src/components/Cart/index.js
  packages/yomerco-web/src/components/Cart/styles.js
  packages/yomerco-web/src/components/Drawer/index.js
  packages/yomerco-web/src/components/Drawer/styles.js
  packages/yomerco-web/src/components/Header/index.js
  packages/yomerco-web/src/components/Header/styles.js
  packages/yomerco-web/src/components/Search/index.js
  packages/yomerco-web/src/components/Search/searchBox.js
  packages/yomerco-web/src/components/Search/styles.js
  packages/yomerco-web/src/index.js
  packages/yomerco-web/src/pages/Home/index.js
  packages/yomerco-web/src/pages/Home/styles.js
  packages/yomerco-web/src/registerServiceWorker.js
  packages/yomerco-web/yarn.lock
Labels: enhancement
